// Notebook Modal
export const NOTEBOOK_OPENMODAL = 'NOTEBOOK_OPENMODAL'
export const NOTEBOOK_CLOSEMODAL = 'NOTEBOOK_CLOSEMODAL'
export const NOTEBOOK_UPDATE_STATE = 'NOTEBOOK_UPDATE_STATE'

// Notebook List
export const FETCHNOTEBOOKLIST = ' FETCHNOTEBOOKLIST'
export const ADDNOTEBOOKLIST = 'ADDNOTEBOOKLIST'
export const UPDATENOTEBOOKLIST = 'UPDATENOTEBOOKLIST'
export const NOTEBOOK_UPDATE_ADD_STATE = 'NOTEBOOK_UPDATE_ADD_STATE'
export const NOTEBOOK_SEARCH_ITEM = 'NOTEBOOK_SEARCH_ITEM'

// Telephone List
export const FETCHTELEPHONELIST = 'FETCHTELEPHONELIST'
export const UPDATETELEPHONELIST = 'UPDATETELEPHONELIST'
export const SEARCHTELEPHONEITEM = 'SEARCHTELEPHONEITEM'